### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by smileglobal** [nathanoertel/whmcs-opensrsemail#2]
I followed the setup instructions to use your provisioning module in WHMCS 5.3.12 and when testing it out with a new order when I click Create (under Module Commands) I receive the following:

Module Command Error:
Permission denied

I'm using the correct company admin user, domain, password, and Cluster. Can you provide any insight on this? Thanks!

**Comment by nathanoertel** [comment]
As far as I am aware, the only reason you would be getting a permission denied error is either invalid credentials (admin user, domain, password and cluster) or being a user with insufficient permissions.  I had issues in the beginning figuring out what was the correct set for me.  I was able to get past the Permission Denied error by running through a few options with a quick CLI script to test options until I got to the correct set.  How certain are you that you are using the correct credentials?

**Comment by smileglobal** [comment]
Thanks Nathan. I was actually able to figure it out. I was using the domain
test.com to test with and I guess it didn't like that. Tried a different
domain and then it began working! Great work on this module :-)

It will save me and my customers a great deal of time!

Any way to set the mailbox quota, or view current usage for a certain
mailbox? Those are a couple of features that would be nice to see.

Keep up the good work!

_--Casey James Price
*_A+/Network+ Certified*

360.298.0394

www.smileglobal.com

 https://twitter.com/Smile_Global https://www.facebook.com/smileglobal

**Comment by nathanoertel** [comment]
Thanks, glad to hear you got it sorted out.

The issue is that their API is extremely limited.  There is no way that I can see from their documentation to get the usage from the API and you can only get the quota by sending a request for each mailbox individually.  It would be great if they would add the quota and usage to the mailbox list so I could show that on the list page.  That we kind of need to get on OpenSRS about.  I can add a method for setting the quota.  Do you mind creating a new issue for that and I will get to that as soon as I am able to?
